# Generated by Django 3.2.9 on 2021-11-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=256)),
                ('endereco', models.CharField(max_length=256)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=256)),
                ('data_criacao', models.DateField(null=True)),
            ],
        ),
    ]
